[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_staking = "3wYXL7pNqG36LGL9azTnhg1KJNnpP3Fk1eB1JTcjAZBv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
